### ISSUE TITLE
Is random access worth the cost?

### ISSUE THREAD

**Issue by hugo306** [dalecurtis/image-decoder-api#4]
For animated images (apng, gif, webp) the complete animation is a chain of dependencies from start to finish.

I tested an example 80 frame gif which would use over 250MB to pre-render then 'play' from memory.
Unsurprisingly Chrome and Firefox did not use the strategy of pre-rendering the sequence of frames. Instead they decompress and render the frames over-and-over on-demand as it loops.
This is memory efficient (15MB max), but uses around 20-25% of four modern CPU cores, all the time the tab has focus.

A dev decides that they want the pathological case: retrieve all the frames from ImageDecoder in reverse order.
In my example 80 frame gif, the browser would need to render n*(n+1)/2 = 3240 frames. O(n^2) processing.

Strategy | Notes
------------ | -------------
Any forward sequence | Start immediately. **O(1)** memory. **O(n)** decoding/compositing. Browser can freely schedule/decode ahead, and free memory at will. Dev can ignore frames they don't need.
A single frame | Dev receives n-1 frames they didn't need BUT that work needed to be done anyway. Browser can free completed frames immediately. **O(1)** memory.
Random (Worst-case) | Must wait for complete file to begin. **O(n^2)** work OR **O(n)** memory. Ahead of time decoding swamped by overheads.

#### Conclusion
Frame decoding is naturally FIFO and transform stream like. Defeating this is expensive.

**Comment by dalecurtis** [comment]
Are you suggesting we note this in the explainer? Or modifying the API to try and prevent such usage? Even if we didn't have random access an author could simply save all the frames as they come out sequentially, so the author can still hoard memory.

Implementations could always impose some limit on the number of outstanding frames if we want to try and curtail this behavior. We'd need some explicit freeing mechanism beyond relying on GC then since it'd otherwise be unreliable.

Under the hood I would expect browsers to maintain a evictable cache of the of the decode outputs, so compute complexity shouldn't exist for random access. Chrome already has to do this so that we can get back to the correct frame on tab switches etc.

So ultimately I land on the side of letting folks shoot themselves in the foot if that's a use case they really have. We'll make things as efficient as possible under the hood since we already need to support similar use cases in the browser.

**Comment by dalecurtis** [comment]
Going to close this issue as I think the random access should be appropriately cached under the hood (and already has to be for normal <img> in modern browsers)

**Comment by LeonScroggins** [comment]
I think we should consider an API that is more focused on sequential access. You're right - an author could still save all the frames as they decode the animation, using more memory. They can do this regardless of the API we provide, but I think that's a good thing. It should be obvious to them that they are using more memory, and they're in the right position to make that decision. Storing all the frames means that if they're looping the animation, they'll use less CPU than if they re-decoded on the second loop.

Random access comes with hidden costs. The naive approach to decoding frame `N` without having previously decoded `0..N-1` would be to decode all of them in order. But Blink currently reads through the stream ahead of time to compute and store frame dependencies, so that it can simulate random access. There still might be some surprises; decoding frame `i` might be significantly faster than decoding frame `j`, simply because `i` is independent, whereas `j` requires decoding many other frames first.

> Under the hood I would expect browsers to maintain a evictable cache of the of the decode outputs, so compute complexity shouldn't exist for random access.

Are you suggesting that the client of the API can evict the cache, or that the browser can? The former seems like a complicated API, and the latter means that the client doesn't have control over the cache. 

> random access should be appropriately cached under the hood (and already has to be for normal  in modern browsers)

What is "appropriate"? I think that depends on the client. Let's say frame `N` depends on frame `N-1`, and the client asks for `N` followed by `N-1`. `Blink::ImageDecoder` will first decode `N-1` and then immediately decode `N`. But it will not (unless I've missed a change since I was last working in this area) continue to cache `N-1`. Then the request to decode `N-1` comes in, and `Blink::ImageDecoder` will decode it again starting from scratch.

(Sorry for the late reply!)

**Comment by dalecurtis** [comment]
> I think we should consider an API that is more focused on sequential access. 

The problem with only having a sequential API is that a client can't implement seeking in animations with non-keyframes efficiently then (without keeping everything in memory after a full decode).

>There still might be some surprises; decoding frame i might be significantly faster than decoding frame j, simply because i is independent, whereas j requires decoding many other frames first.

While folks unfamiliar with seeking in media formats may be surprised at the costs, I think that's okay. If they want dependable behavior they can cache all the frames in JavaScript after decoding sequentially.

> Are you suggesting that the client of the API can evict the cache, or that the browser can? The former seems like a complicated API, and the latter means that the client doesn't have control over the cache.

The browser can evict the cache; which is the ideal spot to be in these days. If the client wants guaranteed caching they can hold a reference on the decoded frame themselves. For those who don't care, if the browser needs to reclaim memory for system pressures it can.

> > random access should be appropriately cached under the hood (and already has to be for normal  in modern browsers)
> 
> What is "appropriate"? I think that depends on the client.

Appropriate means implementation specific in this case. The spec won't define what that means. IIRC, Blink is still caching N-1 unless the cache exceeds |max_decoded_bytes_| which is defined [here](https://source.chromium.org/chromium/chromium/src/+/master:content/child/blink_platform_impl.cc;l=255;drc=aace0cfef2d51e7f038b07d5df26d126e4160f70)
