### ISSUE TITLE
Consider aligning `ImageDecoder`’s `isTypeSupported` with `MediaSource`’s — promise-based vs. synchronous

### ISSUE THREAD

**Issue by mathiasbynens** [dalecurtis/image-decoder-api#6]
(Moved from https://bugs.chromium.org/p/chromium/issues/detail?id=1197269#c8)

Why is `ImageDecoder.isTypeSupported` promise-based and not just synchronous? Is it somehow expensive to figure out whether a given image type is supported?

Making the API synchronously return a boolean instead of a promise would make it consistent with the pre-existing [`isTypeSupported` on `MediaSource`](https://w3c.github.io/media-source/#dom-mediasource-istypesupported). It would also be a more convenient API for developers to use.

**Comment by dalecurtis** [comment]
The API is asynchronous since it must allow for enumeration of hardware image decoders similar to the rest of the WebCodecs API; while today it could easily be synchronous, we could add hardware image decoding support in the future. For implementations which want to provide something like image/heif there may not be a software codec available.

@chcunningham

**Comment by mathiasbynens** [comment]
I understand that _actual image decoding_ might depend on another process, but answering the question "do I know what to do with this image type at all (without necessarily doing the work)" seems orthogonal to that. Couldn't browsers just maintain a list of supported image types they support and synchronously check it whenever `isTypeSupported` is called?

**Comment by Kaiido** [comment]
@mathiasbynens how would you handle an external graphic card (eGPU) being plugged in after the page load? The decoder could only be part of that eGPU's API, and thus not available until the eGPU is plugged in.
